channels:
- conda-forge
dependencies:
- python=3.9.12
- pip<=25.3
- pip:
  - mlflow==3.1.4
  - numpy==1.21.5
  - pandas==1.4.2
  - psutil==5.8.0
  - scikit-learn==1.6.1
  - scipy==1.7.3
  - xgboost==2.1.4
name: mlflow-env
