services:
  s3:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - AWS_DEFAULT_REGION=eu-west-1
    volumes:
      - "./localstack-data:/var/lib/localstack"   # <- persist S3 files here
      - "/var/run/docker.sock:/var/run/docker.sock"