name: CI_Tests
on:
  pull_request:
    branches:
      - 'develop'
    paths:
      - '06-best-practices/code/**'

env:
    AWS_DEFAULT_REGION: "eu-west-1"
    AWS_ACCESS_KEY_ID: "abc"
    AWS_SECRET_ACCESS_KEY: "xyz"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        working-directory: 06-best-practices/code
        run: |
          pip install pipenv && pipenv install --dev

      - name: Run unit tests
        working-directory: 06-best-practices/code
        run: |
          pipenv run pytest tests/

      - name: Lint
        working-directory: 06-best-practices/code
        run: |
          pipenv run pylint --recursive=y .

      # --- Install Docker Compose ---
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version
    
      # --- Set required environment variables for Docker Compose
      - name: Set LOCAL_IMAGE_NAME and PREDICTIONS_STREAM_NAME
        run: |
          echo "LOCAL_IMAGE_NAME=backend-ci:latest" >> $GITHUB_ENV
          echo "PREDICTIONS_STREAM_NAME=predictions-stream" >> $GITHUB_ENV

      # --- Build backend image if needed
      - name: Build backend Docker image
        working-directory: 06-best-practices/code/integration-test
        run: |
          docker build -t backend-ci:latest ..

      # --- Start LocalStack using docker-compose ---
      - name: Start LocalStack
        working-directory: 06-best-practices/code/integration-test
        run: |
          docker-compose up -d
          sleep 10

      # --- Run Integration Tests ---
      - name: Integration tests
        working-directory: 06-best-practices/code/integration-test
        run: |
          ./run.sh